name: invoke_hello_world_workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  invoke_hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hello World workflow
        uses: ./.github/workflows/parameterised_workflow.yaml@main
        with:
          message: "Hello from invoking workflow!"
          recipient: "Anshul"
