name: invoke_workflow.yaml

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: ./.github/workflows/parameterised_workflow.yaml
    with:
      username: Anshul
    secrets:
      token: ${{ secrets.TOKEN }}

